version = 0.1

[default.deploy.parameters]
stack_name = "coagent-suite-landing"
resolve_s3 = true
s3_prefix = "coagent-suite-landing"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = ""
